select * from [dbo].[Brands]
select * from [dbo].[DepartmentProducts]
select * from [dbo].[Departments]
select * from [dbo].[Inventories]
select * from [dbo].[ProductImages]
select * from [dbo].[Products]
select * from [dbo].[ProductVariations]
select * from [dbo].[Reviews]
select * from [dbo].[SelectedItems]
select * from [dbo].[SelectedItemVariations]
select * from [dbo].[ShoppingCarts]
select * from [dbo].[Variations]
select * from [dbo].[VariationTypes]
select * from [dbo].[Warehouses]

--delete from [dbo].[Departments]
--delete from [dbo].[Products]
--delete from [dbo].[Brands]